version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    container_name: infinite-loop-frontend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    container_name: infinite-loop-backend
    # Add memory limit to prevent system crash
    deploy:
      resources:
        limits:
          memory: 1G